[package]
name = "play-integration-xiaozhi"
version = "0.1.0"
edition = "2021"
description = "Xiaozhi MCP integration client for play"

[dependencies]
# Core dependencies
play-mcp = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# WebSocket dependencies
tokio-tungstenite = { workspace = true }
futures = { workspace = true }
