[package]
name = "play-dylib-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
tokio = {workspace = true}
play-abi={path= "../play-abi" }
anyhow={workspace = true}
reqwest = {workspace = true}
log = "0.4.22"
serde_json = "1.0.128"