[package]
name = "play-dylib-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
tokio = {workspace = true}
play-shared={path= "../play-shared" }
anyhow={workspace = true}
reqwest = {workspace = true}