[package]
name = "play-utils-data-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
