server_port = 3000
redis_uri = ["redis://127.0.0.1"]
upgrade_url = "https://github.com/zhouzhipeng/play/releases/download/1.0/play"
log_level = "DEBUG"

[database]
url=":memory:"

[https_cert]
https_port=443
domains = ["xx.xx.com"]
emails = ["xx@xx.com"]

[email_server_config]
port = 25
black_keywords = [""]
