[package]
name = "play-dylib-example"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]


[dependencies]
play-shared={path= "../play-shared" }
reqwest = {workspace = true}
anyhow = {workspace = true}
tokio = {workspace = true}