[package]
name = "tool"
version = "0.1.0"
edition = "2021"


[dependencies]
current_platform="0.2.0"
zip_archive = "1.2.2"
anyhow = { workspace=true }
play-shared={workspace = true}
serde_json = "1.0.109"