[package]
name = "tool"
version = "0.1.0"
edition = "2021"


[dependencies]
pyoxidizer = "0.24.0"
current_platform="0.2.0"
zip_archive = "1.2.2"
anyhow = { workspace=true }
pyo3 = { workspace=true }
shared={path="../libs/shared" , features = ["utils"]}
serde_json = "1.0.109"