# see: https://doc.rust-lang.org/cargo/reference/config.html
[build]
rustflags = ["-Awarnings"]  #keep it uncomment to make wasm build success


[future-incompat-report]
frequency = "never"



[alias]
dev_server = "build --locked --package play-server --release --features=server"

