# see: https://doc.rust-lang.org/cargo/reference/config.html
[build]
rustflags = ["-Awarnings"]  #keep it uncomment to make wasm build success


[future-incompat-report]
frequency = "never"



[alias]
tool = "run --package tool  --bin tool"
pack = "run --package tool --bin pack_bundles"
python = "run --package tool  --bin build_python_artifacts"
dev_embed = "run --package tool  --bin dev_embed"
dev_server = "run --package tool  --bin dev_server"
dev_ui = "run --package tool  --bin dev_ui"
dev = "build --package play-server --release"
debug = "run --package play-server --bin play-server --features=debug"
linux = "build --package play-server  --target=x86_64-unknown-linux-musl --release"
generate = "run --package tool  --bin generate_code"
