# see: https://doc.rust-lang.org/cargo/reference/config.html
[build]
rustflags = ["-Awarnings"]  #keep it uncomment to make wasm build success


[future-incompat-report]
frequency = "never"



[alias]
dev_server = "build --locked --package play-server --release --features=play-dylib-loader,play-lua,play-redis,play-integration-xiaozhi"
dev = "build --package play-server --release"
debug = "run --package play-server --bin play-server --features=debug"
linux = "build --package play-server  --target=x86_64-unknown-linux-musl --release"
generate = "run --package tool  --bin generate_code"
