[package]
name = "play-lua"
version = "0.1.0"
edition="2024"

[dependencies]
reqwest = { workspace = true }
mlua = { version = "0.10", features = ["lua54", "vendored", "async", "send", "serialize", "macros"] }
serde_json = "1.0.140"


[dev-dependencies]
tokio = {workspace = true}