[package]
name = "play-lua"
version = "0.1.0"
edition="2024"

[dependencies]
reqwest = { workspace = true }
mlua = { workspace = true }
serde_json = { workspace = true }
play-shared = {workspace = true}


[dev-dependencies]
tokio = {workspace = true}