name: Build Cache Docker Image

on:
  push:
    branches: [ "cache" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scripts/dockerfiles/cache.Dockerfile
          push: true
          tags: ghcr.io/zhouzhipeng/play-cache:latest
          no-cache: false
          pull: true

      - name: Check build result
        if: failure()
        run: |
          echo "Docker build failed!"
          exit 1